# Setting up the GPT Model

import openai

openai.api_key = "your_openai_api_key"

# Executing the Generated Query in the Database

from db import DB_CONTEXT

dbContext = DB_CONTEXT()

def execute_first_query(prompt_text):
    sql_query = get_predicted_query(gpt, prompt_text)
    queries = sql_query.split("\n")
    first_query = None
    for query in queries:
        if query.startswith("A:"):
            first_query = query[3:].strip()
            break

    if first_query:
        try:
            result = dbContext.cursor(first_query)
            return {"result": result}
        except Exception as e:
            dbContext.connection.rollback()
            return {"error": str(e)}
    else:
        return {"error": "No query found in the response"}
    
# Creating the Gradio UI

import gradio as gr
from model import model, get_predicted_query

gpt = model()

def execute_first_query(prompt_text):
    sql_query = get_predicted_query(gpt, prompt_text)
    # Add your code here to execute the SQL query and return the results
    return {"query": sql_query}

iface = gr.Interface(
    fn=execute_first_query,
    inputs="text",
    outputs="json",
    title="Execute First Query",
    description="Enter a question to execute the first SQL query generated by the model."
)

iface.launch()